/** Stitch design tokens — see src/stitch_diskscope_material_ui/diskscope/DESIGN.md */

export const stitchColors = {
  surface: '#f8f9fa',
  surfaceDim: '#d9dadb',
  surfaceBright: '#f8f9fa',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f3f4f5',
  surfaceContainer: '#edeeef',
  surfaceContainerHigh: '#e7e8e9',
  surfaceContainerHighest: '#e1e3e4',
  onSurface: '#191c1d',
  onSurfaceVariant: '#414754',
  inverseSurface: '#2e3132',
  inverseOnSurface: '#f0f1f2',
  outline: '#727785',
  outlineVariant: '#c1c6d6',
  surfaceTint: '#005bc0',
  primary: '#005bbf',
  onPrimary: '#ffffff',
  primaryContainer: '#1a73e8',
  onPrimaryContainer: '#ffffff',
  inversePrimary: '#adc7ff',
  secondary: '#5b5f64',
  onSecondary: '#ffffff',
  secondaryContainer: '#dde0e6',
  onSecondaryContainer: '#5f6368',
  tertiary: '#0656cf',
  onTertiary: '#ffffff',
  tertiaryContainer: '#3670e9',
  onTertiaryContainer: '#ffffff',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  background: '#f8f9fa',
  onBackground: '#191c1d',
  surfaceVariant: '#e1e3e4',
} as const;

export const stitchDarkColors = {
  surface: '#1f1f1f',
  surfaceDim: '#141414',
  surfaceBright: '#383838',
  surfaceContainerLowest: '#0f0f0f',
  surfaceContainerLow: '#1a1a1a',
  surfaceContainer: '#242424',
  surfaceContainerHigh: '#2e2e2e',
  surfaceContainerHighest: '#383838',
  onSurface: '#e3e2e6',
  onSurfaceVariant: '#c4c6d0',
  inverseSurface: '#e3e2e6',
  inverseOnSurface: '#2e3132',
  outline: '#8e9099',
  outlineVariant: '#44474f',
  surfaceTint: '#adc7ff',
  primary: '#adc7ff',
  onPrimary: '#001a41',
  primaryContainer: '#1a73e8',
  onPrimaryContainer: '#ffffff',
  inversePrimary: '#005bbf',
  secondary: '#c3c7cc',
  onSecondary: '#181c20',
  secondaryContainer: '#43474c',
  onSecondaryContainer: '#dfe3e8',
  tertiary: '#b2c5ff',
  onTertiary: '#001847',
  tertiaryContainer: '#3670e9',
  onTertiaryContainer: '#ffffff',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  background: '#1f1f1f',
  onBackground: '#e3e2e6',
  surfaceVariant: '#44474f',
} as const;

export const layout = {
  gutter: 24,
  sidebarRail: 80,
  sidebarWidth: 280,
  marginMobile: 16,
  marginDesktop: 32,
  topAppBarHeight: 48,
  titleBarHeight: 40,
  scanStatusHeight: 48,
  contentMaxWidth: 1600,
} as const;

export const radii = {
  sm: 4,
  md: 8,
  lg: 16,
  xl: 24,
  full: 9999,
} as const;

export const fonts = {
  ui: '"Geist", system-ui, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;
