export const IPC_CHANNELS = {
  SELECT_DIRECTORY: 'disk-scope:select-directory',
  START_SCAN: 'disk-scope:start-scan',
  CANCEL_SCAN: 'disk-scope:cancel-scan',
  REVEAL_PATH: 'disk-scope:reveal-path',
  COPY_PATH: 'disk-scope:copy-path',
  LIST_DIRECTORY_CONTENTS: 'disk-scope:list-directory-contents',
  DELETE_PATH: 'disk-scope:delete-path',
  EXPORT_REPORT: 'disk-scope:export-report',
  GET_PREFERENCES: 'disk-scope:get-preferences',
  SET_PREFERENCES: 'disk-scope:set-preferences',
  SCAN_PROGRESS: 'disk-scope:scan-progress',
  SCAN_COMPLETE: 'disk-scope:scan-complete',
  SCAN_ERROR: 'disk-scope:scan-error',
  WINDOW_MINIMIZE: 'disk-scope:window-minimize',
  WINDOW_TOGGLE_MAXIMIZE: 'disk-scope:window-toggle-maximize',
  WINDOW_CLOSE: 'disk-scope:window-close',
  WINDOW_IS_MAXIMIZED: 'disk-scope:window-is-maximized',
  WINDOW_MAXIMIZE_CHANGED: 'disk-scope:window-maximize-changed',
  GET_E2E_AUTOSTART_CONFIG: 'disk-scope:get-e2e-autostart-config',
} as const;
