export const IPC_CHANNELS = {
  SELECT_DIRECTORY: 'disk-scope:select-directory',
  START_SCAN: 'disk-scope:start-scan',
  CANCEL_SCAN: 'disk-scope:cancel-scan',
  REVEAL_PATH: 'disk-scope:reveal-path',
  COPY_PATH: 'disk-scope:copy-path',
  LIST_DIRECTORY_CONTENTS: 'disk-scope:list-directory-contents',
  DELETE_PATH: 'disk-scope:delete-path',
  EXPORT_REPORT: 'disk-scope:export-report',
  GET_PREFERENCES: 'disk-scope:get-preferences',
  SET_PREFERENCES: 'disk-scope:set-preferences',
  GET_SCAN_HISTORY: 'disk-scope:get-scan-history',
  SAVE_LAST_SELECTED_PATHS: 'disk-scope:save-last-selected-paths',
  SCAN_PROGRESS: 'disk-scope:scan-progress',
  SCAN_COMPLETE: 'disk-scope:scan-complete',
  SCAN_ERROR: 'disk-scope:scan-error',
  WINDOW_MINIMIZE: 'disk-scope:window-minimize',
  WINDOW_TOGGLE_MAXIMIZE: 'disk-scope:window-toggle-maximize',
  WINDOW_CLOSE: 'disk-scope:window-close',
  WINDOW_IS_MAXIMIZED: 'disk-scope:window-is-maximized',
  WINDOW_MAXIMIZE_CHANGED: 'disk-scope:window-maximize-changed',
  CHECK_FOR_UPDATES: 'disk-scope:check-for-updates',
  INSTALL_UPDATE: 'disk-scope:install-update',
  GET_UPDATE_STATUS: 'disk-scope:get-update-status',
  UPDATE_STATUS: 'disk-scope:update-status',
} as const;
