/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeDirectoryEntry {
  name: string
  path: string
  isDirectory: boolean
  isSymlink: boolean
  sizeBytes: number
  mtimeMs?: number
}
export declare function readDirectory(dirPath: string): Array<NativeDirectoryEntry>
